<table>
  <thead>
    <td>№</td>
    <td>Название</td>
    <td>Программа</td>
    <td>Статус</td>
    <td>Время</td>
    <td>Остановить</td>
    <td>Удалить</td>
  </thead>
  <tbody>
    <td>22</td>
    <td>23</td>
    <td>24</td>
    <td>25</td>
    <td>26</td>
    <td>27</td>
    <td>28</td>
  </tbody>
</table>
